topsport-com-au/starlite-saqlalchemy

src/starlite_lib/starlite/middleware.py
Adds debug logging to session interactions to aid debugging db resource interaction.
=> Debug logging around session management middleware.

.github/workflows/docs.yml
=> docs: build on tag and use `github.ref_name` for version.

docs/index.md, mkdocs.yml, poetry.lock, pyproject.toml, src/starlite_saqlalchemy/init_plugin.py, src/starlite_saqlalchemy/repository/abc.py, src/starlite_saqlalchemy/repository/sqlalchemy.py, src/starlite_saqlalchemy/service.py, src/starlite_saqlalchemy/worker.py, tests/unit/repository/test_sqlalchemy.py, tests/unit/test_service.py, tests/unit/utils.py, tests/utils/controllers.py, tests/utils/domain.py, tox.ini
Adds an async callback pattern for each operation.
Documents overall app pattern.
=> feat: Service object callback pattern

poetry.lock, pyproject.toml, src/starlite_saqlalchemy/worker.py
- depend on SAQ master branch from GH until typed version released
- fix typing for worker module
=> fix(worker): Depend on typed SAQ

src/starlite_saqlalchemy/cache.py, src/starlite_saqlalchemy/dependencies.py, src/starlite_saqlalchemy/dto.py, src/starlite_saqlalchemy/http.py, src/starlite_saqlalchemy/orm.py, src/starlite_saqlalchemy/repository/sqlalchemy.py, src/starlite_saqlalchemy/repository/types.py, src/starlite_saqlalchemy/response.py, src/starlite_saqlalchemy/service.py, src/starlite_saqlalchemy/settings.py, src/starlite_saqlalchemy/worker.py
Google style everywhere.
Closes #24
=> chore(docs): consistent docstring format.

.github/workflows/ci.yml, .github/workflows/codeql.yml, .github/workflows/docs.yml
=> ci(actions): comment version tag of git hash.

.pre-commit-config.yaml, src/starlite_saqlalchemy/cache.py, src/starlite_saqlalchemy/compression.py, src/starlite_saqlalchemy/dependencies.py, src/starlite_saqlalchemy/dto.py, src/starlite_saqlalchemy/endpoint_decorator.py, src/starlite_saqlalchemy/exceptions.py, src/starlite_saqlalchemy/http.py, src/starlite_saqlalchemy/init_plugin.py, src/starlite_saqlalchemy/logging.py, src/starlite_saqlalchemy/openapi.py, src/starlite_saqlalchemy/redis.py, src/starlite_saqlalchemy/repository/__init__.py, src/starlite_saqlalchemy/repository/abc.py, src/starlite_saqlalchemy/repository/exceptions.py, src/starlite_saqlalchemy/repository/filters.py, src/starlite_saqlalchemy/repository/sqlalchemy.py, src/starlite_saqlalchemy/repository/types.py, src/starlite_saqlalchemy/response.py, src/starlite_saqlalchemy/sentry.py, src/starlite_saqlalchemy/service.py, src/starlite_saqlalchemy/settings.py, src/starlite_saqlalchemy/sqlalchemy_plugin.py, src/starlite_saqlalchemy/static_files.py, src/starlite_saqlalchemy/worker.py
Applied the forward ref annotations wherever possible. Issues with starlite dependencies and handlers, and with sqlalchemy orm, so not applied to those modules.
=> chore(types): from __future__ import annotations

README.md
Tried to add a docs badge but couldn't get it to work.
Closes #56
Closes #67
=> docs(readme): fix badges.

dev.requirements.txt, docs.requirements.txt
=> chore(dependabot): Pin dev and docs dependency versions.

.github/dependabot.yml
=> chore(dependabot): add "pip" package-ecosystem

src/starlite_saqlalchemy/cache.py, src/starlite_saqlalchemy/dependencies.py, src/starlite_saqlalchemy/exceptions.py, src/starlite_saqlalchemy/logging.py, src/starlite_saqlalchemy/redis.py, src/starlite_saqlalchemy/repository/abc.py, src/starlite_saqlalchemy/repository/sqlalchemy.py, src/starlite_saqlalchemy/repository/types.py, src/starlite_saqlalchemy/response.py, src/starlite_saqlalchemy/service.py
=> chore(types): Typing improvements from pyright --analyzetypes

src/starlite_saqlalchemy/testing/repository.py, tests/unit/conftest.py, tests/unit/repository/test_abc.py
Includes a `GenericMockRepository` instance for testing.
Closes #50
=> feat(testing): create a `testing` sub-package.

docs/async_worker.md, docs/index.md, src/starlite_saqlalchemy/service.py, tests/unit/test_service.py
Adds docs.
Closes #14
Closes #89
=> feat(worker): improves the worker pattern.

.github/workflows/ci.yml, src/starlite_saqlalchemy/service.py, tox.ini
I don't want to preempt the requirements here until I get the user
model integrated.
There are some specific requirements that I will have for being able
to control the attributes that may be modified by a user depending on
their type and the model, so I don't want to suppose anything about
that implementation.
=> feat(service)!: Simplify service

.github/workflows/ci.yml, sonar-project.properties
=> ci(sonar): configure sonarcloud ci

src/starlite_saqlalchemy/repository/abc.py, src/starlite_saqlalchemy/repository/sqlalchemy.py, src/starlite_saqlalchemy/service.py, src/starlite_saqlalchemy/testing.py, tests/unit/repository/test_sqlalchemy.py, tests/unit/test_service.py, tests/utils/domain.py
Was all just a bit too magic. Would rather keep it simple for now and see how it evolves.
=> feat!: simplify service and repo.

.flake8, src/starlite_saqlalchemy/testing.py, tests/conftest.py, tests/unit/conftest.py, tests/unit/test_dto.py, tests/unit/test_orm.py, tests/unit/test_service.py, tests/unit/test_testing.py, tests/utils/controllers.py, tests/utils/domain/__init__.py, tests/utils/domain/authors.py, tests/utils/domain/books.py
Adds model type collection namespacing so that multiple types aren't competing for the same namespace.
=> fix(testing): fix GenericMockRepository collections.

src/starlite_saqlalchemy/dto/from_mapped.py, tests/unit/test_dto.py
Hotfix for current impl. of DTO to fix inference of UnionType, e.g., `str | None`.
=> fix(dto): Fix UnionType parsing as relationship.

src/starlite_saqlalchemy/scripts.py
=> feat: enable toggling of db/cache checks in run-app script.

.pre-commit-config.yaml, src/starlite_saqlalchemy/compression.py, src/starlite_saqlalchemy/db/__init__.py, src/starlite_saqlalchemy/db/orm.py, src/starlite_saqlalchemy/dto/types.py, src/starlite_saqlalchemy/init_plugin.py, src/starlite_saqlalchemy/log/__init__.py, src/starlite_saqlalchemy/openapi.py, src/starlite_saqlalchemy/redis.py, src/starlite_saqlalchemy/repository/filters.py, src/starlite_saqlalchemy/settings.py, src/starlite_saqlalchemy/worker.py, tests/utils/domain/books.py
The docformatter update included a change to format class attribute docstrings, so many fixes for that included here.
=> chore(linting): update pre-commit hooks

src/starlite_saqlalchemy/exceptions.py, tests/unit/test_exceptions.py
=> fix(logging): don't log exc info for client errors.

poetry.lock, pyproject.toml, requirements.dev-extras.txt
Thought we can add that to 0.29 as well ;)
=> build(deps): update sqlachemy to 2.0.0rc3
